macro(detectOS)
    if (WIN32)
        set(APPLICATION_TYPE)
        add_compile_definitions(OS_WINDOWS)
    elseif (APPLE)
        add_compile_definitions(OS_MACOS)
        set(APPLICATION_TYPE MACOSX_BUNDLE)
    elseif (UNIX AND NOT APPLE)
        add_compile_definitions(OS_LINUX)
    endif()
endmacro()